version: '3.9'
services:
  nginx:
    image: 'nginx:1.26-alpine'
    container_name: wp-nginx
    expose:
      - '80'
    depends_on:
      - php
    volumes:
      - './wordpress:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - 'nginx_cache:/var/cache/nginx'
    restart: unless-stopped
  php:
    image: 'wordpress:php8.5-fpm-alpine'
    container_name: wp-php
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - './wordpress:/var/www/html'
      - './php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini'
    restart: unless-stopped
  db:
    image: 'mariadb:12'
    container_name: wp-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db_data:/var/lib/mysql'
    command:
      - '--innodb-buffer-pool-size=1G'
      - '--innodb-flush-log-at-trx-commit=2'
    restart: unless-stopped
  redis:
    image: 'redis:7-alpine'
    container_name: wp-redis
    restart: unless-stopped
volumes:
  db_data: null
  nginx_cache: null
